# Generated by Django 2.2.2 on 2020-05-02 16:39

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_vacationrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vacationrequest',
            name='reviewed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vacationrequest',
            name='status',
            field=models.CharField(choices=[(accounts.models.StatusChoice('Requested'), 'Requested'), (accounts.models.StatusChoice('Approved'), 'Approved'), (accounts.models.StatusChoice('Denied'), 'Denied')], max_length=5),
        ),
    ]
